In [3]:
import numpy as numpy

array1 =numpy.array([[1,2,3],[4,5,6]])
print(array1.size)

6


In [4]:
import numpy as numpy

array2=numpy.array([[12,13,14],[15,16,17]])
print(array2.shape)

(2, 3)


In [8]:
array3=numpy.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(array3.shape)
print(array3.dtype)

(2, 2, 3)
int64


In [11]:
array =numpy.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array.ndim)  #arraytype output 3


3


In [13]:
array0=numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array0[1,2])  #print the array index

8


In [22]:
# create a 2d array wich has diamension 4:5 which contains the numbers 1 to 20 perform the following on this array at 10 to 18 eleven multi by every element by 
# calculate the squar of each element
array = numpy.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(array[1,3])

9


In [23]:
array=numpy.array([10,20,30,40,50])
condition =array>25
print(condition)

[False False  True  True  True]


In [24]:
array=numpy.array([10,20,30,40,50])
condition =array>25
filterd=array[condition]
print(filterd)

[30 40 50]


In [25]:


arr = numpy.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr>25) & (arr < 50)]  # condition deka eka para chek krla thiynne meke
print(filtered_arr)

[30 40]


In [26]:
arr=numpy.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
array=numpy.full(4,7)
print(array)

[7 7 7 7]


In [28]:
array=numpy.full((2,3),8)
print(array)

[[8 8 8]
 [8 8 8]]
